[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--no-audit --no-fund"

# Optional: turn on Lighthouse plugin in Netlify UI for automated checks
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"
